[package]
name = "math-rs"
version = "0.0.1"

[dependencies]
log = "0.4.20"
env_logger = "^0.9.0"
nalgebra = "0.32.3"
num-traits = "0.2.17"
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "bench"
harness = false